### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by pfitzseb** [JuliaDebug/Infiltrator.jl#1]
for the package and `@varexplode`.

**Comment by aminya** [comment]
Thank you for this package! 
It is similar to what I requested here in https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/298.

Maybe @fastdebug ?

**Comment by BeastyBlacksmith** [comment]
What about `Infiltrator.jl`?

**Comment by pfitzseb** [comment]
Infiltrator.jl and `@infiltrate`? I kinda like it, tbh :D

**Comment by pfitzseb** [comment]
I think I like Infiltrator.jl/`@infiltrate` and GiveMeAPrompt.jl/`@prompt` the best so far.

**Comment by aminya** [comment]
I wish we could change @infiltrator macro's name to something simpler. I always get the spelling incorrect.

**Comment by BeastyBlacksmith** [comment]
`@stab` 🗡 😄

**Comment by Infiltrator** [comment]
Indeed, @aminya.  Especially since GitHub will tag random users.  ;)
