### ISSUE TITLE
Suggested API addition: @infiltry

### ISSUE THREAD

**Issue by fredcallaway** [JuliaDebug/Infiltrator.jl#115]
I find this macro to be very useful, maybe worth adding to the package?

Saves a lot of time over manually writing out the try block while debugging.

```julia
macro infiltry(ex)
    return quote
        try
            $(esc(ex))
        catch
            $(Infiltrator.start_prompt)($(__module__), Base.@locals, $(String(__source__.file)), $(__source__.line))
        end
    end
end
```

**Comment by pfitzseb** [comment]
Sure, looks good. Not sure I like the name overmuch, but can't think of a better alternative. Wanna open a PR?
