### ISSUE TITLE
Resolving "Infiltrator.jl needs a fully-functional Julia REPL."

### ISSUE THREAD

**Issue by arch-dawson** [JuliaDebug/Infiltrator.jl#129]
I am receiving this error but I am unsure what a "fully-functional Julia REPL" is.

Contents of startup.jl
```julia
using Infiltrator
using Revise
```

Contents of basic.jl
```julia
#!/usr/bin/env -S julia --color=yes --startup-file=yes -i

function add_two(x)
    Main.@infiltrate
    x + 2
end

add_two(2)
```

From the command line I run `./basic.jl`, but I receive the error `Infiltrator.jl needs a fully-functional Julia REPL.`. Is the Julia REPL running in a shell terminal not "fully functional"? Would you mind clarifying what the error message is intending to convey, or what is incorrect in my setup?

**Comment by pfitzseb** [comment]
The issue here is that `-i` does not start the REPL before running the code in `basic.jl` (or that given in `-e`, if applicable). Infiltrator needs all REPL setup to be completed to be functional though. The solution here is to start a REPL and then `include()` your file manually.

**Comment by arch-dawson** [comment]
That worked, thank you!
