### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaDebug/Infiltrator.jl#13]
@pfitzseb What do you think about tagging a new release of Infiltrator.jl? It would be great to have the `@stop` functionality from https://github.com/JuliaDebug/Infiltrator.jl/pull/6 available in a tagged release.

**Comment by pfitzseb** [comment]
https://github.com/JuliaRegistries/General/pull/4100

**Comment by DilumAluthge** [comment]
Closed by https://github.com/JuliaRegistries/General/pull/4100
