### ISSUE TITLE
Buggy REPL when @infiltrate is hit

### ISSUE THREAD

**Issue by aminya** [JuliaDebug/Infiltrator.jl#14]
![infiltrator](https://user-images.githubusercontent.com/16418197/66298543-8fc19b00-e8b7-11e9-8fd8-48d36ec14bd2.gif)
I click run all button, and `@infiltrate` is hit. But when I try to type `@locals`, you see that REPL returns back to julia from debug, and `@locals` isn't typed correctly!

**Comment by pfitzseb** [comment]
Yeah, you need to call the function from the REPL (basically because of https://github.com/JunoLab/Juno.jl/issues/118).

**Comment by aminya** [comment]
Calling the function from the REPL is not a good solution. In other languages (e.g. Matlab), people run and debug the same way, and they don't adjust their running behavior for debugging.

Can't we programmatically type a new line?
Like:
https://github.com/juliamatlab/MatLang/blob/4598efdcfd0d575ceb67e4ea5d8af09f6fa8046b/src/MatLang.jl#L19-L20
or
https://github.com/juliamatlab/MatLang/blob/4598efdcfd0d575ceb67e4ea5d8af09f6fa8046b/src/Language_Fundamentals/Entering_Commands.jl#L19

**Comment by pfitzseb** [comment]
Sure, that's not a problem. But you can't (or at least: I haven't figured out a way to) switch REPL modes from another task.

**Comment by aminya** [comment]
I cannot use `@infiltrate` anymore in Julia 1.3. The REPL mode doesn't change at all.

**Comment by pfitzseb** [comment]
I can't repro this -- Infiltrator works the same for me on 1.3 (both the buggy behaviour from inline evaluation and the expected behaviour from REPL evaluation).

**Comment by aminya** [comment]
It happened inside a `do` block in a `for` loop/
Putting `@infiltrate` before this line:
https://github.com/aminya/StaticCompiler.jl/blob/3c7ed69348bb1ee222e7d417906ef18c0553597d/test/standalone-exe.jl#L125
