### ISSUE TITLE
@stop doesn't do anything

### ISSUE THREAD

**Issue by aminya** [JuliaDebug/Infiltrator.jl#15]
When I run `@stop` nothing happens. I use Infiltrator v0.2.0

```julia
debug> @stop

debug> 
```

**Comment by DilumAluthge** [comment]
`@stop` means that you won’t infiltrate at that same location in the future.

**Comment by aminya** [comment]
So how can I exit from debugging mode? I thought `@stop` does that

**Comment by pfitzseb** [comment]
`Ctrl-C` (or `Ctrl-D`) should do the trick, same as every other REPL mode.

**Comment by aminya** [comment]
I see, thank you!
