### ISSUE TITLE
Could you please document usage inside modules?

### ISSUE THREAD

**Issue by juliohm** [JuliaDebug/Infiltrator.jl#17]
I saw the thread on discourse where it was suggested to first load `using Infiltrator` in the script, and then add `Main.Infiltrator.@infiltrate` inside an existing module being developed. For some reason the `Infiltrator` is not recognised in the `Main` module and I wonder if I am doing something wrong? A step-by-step on how to infiltrate existing modules in the dev folder is appreciated in the README.md

**Comment by juliohm** [comment]
Any help is appreciated.

**Comment by pfitzseb** [comment]
Both
```
using Infiltrator

module Foo
function foo(x)
    y = 123
    x = x + y
    Main.@infiltrate
    x
end
end
```
and
```
module Bar
using Infiltrator
function foo(x)
    y = 123
    x = x + y
    @infiltrate
    x
end
end
```
should work fine -- it's just a matter of referring to the module into which you've loaded Infiltrator.

**Comment by juliohm** [comment]
Tnanks, will test later today.
