### ISSUE TITLE
Save used commands 

### ISSUE THREAD

**Issue by Wikunia** [JuliaDebug/Infiltrator.jl#21]
Unfortunately it doesn't seem possible to use the `up` key to see the previous command.
Example I hit `@infiltrate` and want to check the variable `x` and then jump to the next `@infiltrate` and want to inspect `x` again. I need to type `x` instead of just use the `up` key as it works in the REPL.
This is not a problem if it would be just `x` but sometimes it's calling a function and it's a pain to write the same thing again. 
Is this possible/easy to do?

**Comment by pfitzseb** [comment]
The history is now persistent for a julia session.
