### ISSUE TITLE
Incompatibility with VS Code 

### ISSUE THREAD

**Issue by kevin-tracy** [JuliaDebug/Infiltrator.jl#23]
I have been using Infiltrator.jl in Juno for a while, but can't seem to get it to work with VS Code.  The REPL is very buggy and doesn't stay in the `> debug` environment. I am on Mac OSX 10.13.6, running Julia 1.5.2 on VS Code 1.51.1.

**Comment by pfitzseb** [comment]
Yeah... Don't run Infiltrator via inline evaluation; use the REPL only. Nothing to be done about this here, unfortunately.

**Comment by nikolasborrel** [comment]
Not sure what is meant by using only the REPL? The use case is to insert the infiltrate macro in the code and inspect the variables in this part of the code (referred to as 'inline'?) - how to do that using the REPL?

**Comment by nikolasborrel** [comment]
And what is the reason for the glitch? Is it a bug in the VS Code extension?

**Comment by pfitzseb** [comment]
You need to call the function that contains an `@infiltrate` in the REPL, not in the editor. And yes, it's a shortcoming of how we do inline evaluation in VSCode. It's possible to work around, but all solutions I came up with so far are iffy.

**Comment by nikolasborrel** [comment]
Thanks, that works fine! 

I have been rewriting code from Matlab into Julia the last weeks and I like Julia, however, I think the tooling is still missing some core functionalities - such as proper debugging as the most important. The IDE VS Code debugging in Julia is extremely slow and cannot be used, so it would be great to integrate your solution into the IDE (of course, adding breakpoints in the usual way would clearly be preferable)

**Comment by kenahoo** [comment]
Is there a corresponding bug/issue in the VS Code project for this?  It's certainly a bug *somewhere*, and if it's not this project's responsibility then it seems like it needs a ticket over there.
