### ISSUE TITLE
VScode editor integration---glitchy REPL when run directly from the editor

### ISSUE THREAD

**Issue by ElectronicTeaCup** [JuliaDebug/Infiltrator.jl#25]
When running a function with the infiltrator macro from the vscode editor, the REPL becomes glitchy (which is a known issue) and when exiting the debug session, for me at least, Julia crashes quite often. The work around is to run the lines in REPL, but it would be far more easier if this was made possible directly from the editor.

**Comment by pfitzseb** [comment]
Dup of https://github.com/JuliaDebug/Infiltrator.jl/issues/23.
