### ISSUE TITLE
Keystrokes are not detected correctly in VS Code command line

### ISSUE THREAD

**Issue by nikolasborrel** [JuliaDebug/Infiltrator.jl#29]
When hitting an `@infiltrate cond = true` breakpoint, keystrokes are not detected properly:

E.g when writing

    debug> f_detect

the command line changes to

    julia> fdtc

and only after pressing enter a few times, the command line is ready for use in the `debug>` env. It's quite annoying and time-consuming to get the command line ready on every run!

System: 
- VS Code (mac) 1.52.0
- Julia Language Support extension 1.0.10
- Julia 1.5.3

![infiltrate_debug](https://user-images.githubusercontent.com/9203478/102483503-21ed3380-4065-11eb-9c29-d0478b4075bc.png)
![infiltrate_debug_err](https://user-images.githubusercontent.com/9203478/102483518-27e31480-4065-11eb-92eb-be4b0d852105.png)

**Comment by pfitzseb** [comment]
Dup of https://github.com/JuliaDebug/Infiltrator.jl/issues/23.
