### ISSUE TITLE
Variables are persistent inside `@infiltrate` scope

### ISSUE THREAD

**Issue by pdeffebach** [JuliaDebug/Infiltrator.jl#34]
Really appreciate the new behavior in #22!

However I think I've encountered a bug. If a variable is defined inside the `@infiltrate` REPL it doesn't get over-written when that variable is added to the function. 

```
julia> function foo()
           x = 1
           @infiltrate
       end;

julia> foo()
Infiltrating foo() at REPL[26]:3:

debug> y = 100
100

debug> @exit


julia> function foo()
           x = 1
           y = 2
           @infiltrate
       end;

julia> foo()
Infiltrating foo() at REPL[28]:4:

debug> y
100
```

This is a bit annoying because often I enter `@infiltrate` to play around defining variables before I write the code for them. But if they don't update, then I can't add code iteratively.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JuliaDebug/Infiltrator.jl/commit/a582494c21b8bae78dd2fee1914fdad50f235e1a.

**Comment by pdeffebach** [comment]
Is there a reason why these variables are persistent at all? Is it simply too expensive to create a new anonymous module for every `@infiltrate` call? I think it's a bit weird that definitions persist even after `@exit`.

**Comment by pfitzseb** [comment]
Hm, I thought this would be more convenient. It's also fairly hard to tell when a new "session" starts since all `@infiltrate` statements are completely independent. And a separate scratch pad for each `@infiltrate` seems like a bad idea because then it's non-obvious how to access them.

**Comment by pdeffebach** [comment]
Yeah, that makes sense. I think the user can call `clear_scratch_pad` if they want things separate between calls.
