### ISSUE TITLE
Docs ahead of release?

### ISSUE THREAD

**Issue by fredcallaway** [JuliaDebug/Infiltrator.jl#36]
Not sure what's going on here, but I just added Infiltrator (v0.3.0) from the general repository and it's missing a lot of the functionality in the readme (which looks super useful!)

EDIT: For example, there's no `@exfiltrate` macro.

**Comment by pfitzseb** [comment]
Yeah, I'll tag a new release soon. Check https://github.com/JuliaDebug/Infiltrator.jl/tree/v0.3.0 for the proper readme.
