### ISSUE TITLE
Infiltrator not in Package registry

### ISSUE THREAD

**Issue by mattcbro** [JuliaDebug/Infiltrator.jl#4]
This is a much needed capability,  given that Debugger is impossibly slow when doing any array intensive calculations.  Thanks for providing it.

What's the best way to add this to my Julia 1.2.0 installation?  It doesn't appear to be in the package repository,  namely:

```
(v1.2) pkg> add Infiltrator
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: The following package names could not be resolved:
 * Infiltrator (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

**Comment by pfitzseb** [comment]
https://github.com/JuliaRegistries/General/pull/3070

**Comment by mattcbro** [comment]
Perfect thanks.
