### ISSUE TITLE
Showing the `safehouse` variables

### ISSUE THREAD

**Issue by Wikunia** [JuliaDebug/Infiltrator.jl#40]
First of all I really appreciate this package. For me it's the best way of debugging code in Julia atm.

I experimented with the new version yesterday and saw that one only sees the number of variables stored in the `safehouse`. Then one needs to use `safehouse.<TAB>` to see saved variables. Is there a reason to not show the same thing as done with `@locals` to see the saved variables directly?

**Comment by pfitzseb** [comment]
Fixed in https://github.com/JuliaDebug/Infiltrator.jl/commit/7e1624fdc7bb480ccc5ed3132bfdae8f2172a016.

**Comment by Wikunia** [comment]
Awesome!
