### ISSUE TITLE
Indefinite hangs when trying to throw an error

### ISSUE THREAD

**Issue by pdeffebach** [JuliaDebug/Infiltrator.jl#42]
I want to write this issue down, even if I don't have an MWE at the moment, so my gripe doesn't get lost in the slack hole. 

When using `NLSolve` and `try`-`catch` blocks to debug, sometimes I get an error that never prints. It just hangs until I press Ctrl-z. 

This only happens with Infiltrator.jl is loaded. 

Sebastian thinks this has something to do with method overloading that Infiltrator.jl does. This is a bit frustrating for me because I don't use `@infiltrate`, only `@exfiltrate`. Without the presence of `@infiltrate` in the code, I feel like I shouldn't get any of the problems that come from `@infiltrate`. 

I was working on an MWE today but couldn't pinpoint it. Will try again soon.

**Comment by pfitzseb** [comment]
I'll close this for now. Feel free to reopen this or open a new issues if you encounter the bug again.
