### ISSUE TITLE
Infiltrator macro only executes once in main function

### ISSUE THREAD

**Issue by charstnut** [JuliaDebug/Infiltrator.jl#43]
Hi, in a process of trial and error I found that the `@infiltrate` breakpoint in a macro only stops once when called inside another function (e.g. a `main()` function).
A minimal working example is:
```
using Printf
using Infiltrator

# For example (from Julia Reference)
macro sayhellocode(name)
    @infiltrate
    return :(@printf "Hello, %s" $name)
end

function main()
    mac = @macroexpand @sayhellocode("World\n")
    ex = @sayhellocode("World Two\n")
end

main()
```
When run in REPL, with the "include" command for the first time, the two `sayhellocode` macros both give the infil REPL. However afterwards, running `main()` again in the julia REPL drops into only the first `sayhellocode` macro.
Is this a limitation with compiled debugging or is this a bug?

Thanks!

**Comment by pfitzseb** [comment]
That's just the way macros work in Julia. Compare e.g.
```
julia> using Printf

julia> macro sayhellocode(name)
           println("sayhello: ", name)
           return :(@printf "Hello, %s" $name)
       end
@sayhellocode (macro with 1 method)

julia> function main()
           mac = @macroexpand @sayhellocode("World\n")
           ex = @sayhellocode("World Two\n")
       end
sayhello: World Two

main (generic function with 1 method)

julia> main()
sayhello: World

Hello, World Two
```
You can see that `sayhello: World Two` is printed when `main` is *defined*, not when it is called, because the `sayhellocode`  macro is expanded.

So all in all I'd very much recommend using `@infiltrate` in the returned expression instead:
```
julia> using Printf, Infiltrator

julia> macro sayhellocode(name)
           return quote
               @infiltrate
               @printf "Hello, %s" $name
           end
       end
@sayhellocode (macro with 1 method)

julia> function main()
           mac = @macroexpand @sayhellocode("World\n")
           ex = @sayhellocode("World Two\n")
       end
main (generic function with 1 method)

julia> main()
Hit `@infiltrate` in macro expansion at REPL[2]:3 [inlined]:

debug> @trace
[1] macro expansion at REPL[2]:3 [inlined]
[2] main() at REPL[3]:3

debug>

Hello, World Two
```

**Comment by charstnut** [comment]
Thank you! That clears up a lot.
