### ISSUE TITLE
Unable to type commands at the interactive REPL correctly

### ISSUE THREAD

**Issue by dpsanders** [JuliaDebug/Infiltrator.jl#46]
I'm trying to use `Infiltrator.jl` on a particular code-base but am having a problem typing commands at the interactive REPL, e.g. I type

```jl
infil> @locals
```

but what appears on my screen and what Infiltrator interprets is `infil> lcl` which gives an error.
It seems to be ignoring every odd-numbered character in the string. 
When I type `ctrl-D` I then see those characters:

```
infil> @oas
```

(But none of this happens when I try the package with a simple function at the REPL.)

I don't *think* the code-base is doing anything funny. Is there something I can do about this, or something particular I should try to look for?

**Comment by pfitzseb** [comment]
That sounds like you're running functions via inline evaluation. 
> Running code that ends up triggering the `@infiltrate` REPL mode via inline evaluation in VSCode or Juno can cause issues, so it's recommended to always use the REPL directly.

**Comment by dpsanders** [comment]
Nope, I'm running it from a standard Julia REPL.

**Comment by pfitzseb** [comment]
Do you have any `readline` calls or similar STDIN-interactions or any other packages that mess with the REPL loaded?

**Comment by RGerzaguet** [comment]
Hello,
I have the same issue. It seems that the REPL does not interpret the input as it should.
Is is impossible to launch any command or to exit.

For example if I type `a` and `clear` I get a new prompt demand `infilt>`. If I repeatly type on `enter` I get 

```
infil> ##This is when I type `a` + enter. Then `clear`and <enter>. Then I type repeatly type <enter> 
infil>

infil>

infil>

infil>

infil>

infil>

infil>

infil>

infil>

infil>


infil> a # Oh suddently I magically appears 
ERROR: UndefVarError: a not defined
Stacktrace:
 [1] top-level scope
   @ none:1

infil>

infil>

infil>

infil>

infil>

infil>

infil>

infil>

infil> c #clear appear letter after letter when I type <enter>
ERROR: UndefVarError: c not defined
Stacktrace:
 [1] top-level scope
   @ none:1

infil> l
ERROR: UndefVarError: l not defined
Stacktrace:
 [1] top-level scope
   @ none:1

infil> e
ERROR: UndefVarError: e not defined
Stacktrace:
 [1] top-level scope
   @ none:1

infil> a
ERROR: UndefVarError: a not defined
Stacktrace:
 [1] top-level scope
   @ none:1

infil> r
ERROR: UndefVarError: r not defined
Stacktrace:
 [1] top-level scope
   @ none:1
```

Pure REPL session, no `redline`, no STDIN interaction.  I have tried with Infiltrator (latest) and 1.0.0.
Infiltrator is used within a module 

if you need anything else, let me know !

**Comment by pfitzseb** [comment]
Can you share the code that causes this (ideally as minimal as possible)? Basically your whole REPL session + what packages you've loaded and what `@infiltrate` statements are in there.

**Comment by RGerzaguet** [comment]
Thanks for being my rubber duck @pfitzseb 👍
The issue was due (on my side) to the use of `@spwanat` macro. I think that the infiltrate calls stack and interfere each others. 
A minimal working example below. Note that this may not be a bug as infiltrate should not be used this way.  Also note sure if @dpsanders used `spawn`

```
module Issue_Infiltrator

using Infiltrator
using Distributed

function processing(x)
    @infiltrate
    z = x + randn(size(x))
    return z
end
function main_works()
    allTask = []
    for _ ∈ 1 : 100
        x = randn(60_000,16)
        task = @spawnat :any processing(x) ## replace by w = processing(x) to have a functionnal infiltrate
        push!(allTask,task)
    end
    foreach(wait,allTask)
    allW = Int[]
    for t in allTask
        w = fetch(t)
        push!(allW,w)
    end
    return allW
end
end
```

**Comment by pfitzseb** [comment]
Ah, that makes sense.

> That sounds like you're running functions via inline evaluation.

is an issue precisely because `@infilatrate` is called in a separate task.

So yeah, I'll add some checks for the current task.
