### ISSUE TITLE
Allow tab completion of structs in the infiltrated REPL

### ISSUE THREAD

**Issue by dpsanders** [JuliaDebug/Infiltrator.jl#47]
It would be very useful to be able to use tab completion for discovering / introspecting fields of `struct`s in the infiltrated REPL, e.g. `a.<TAB> would list the fields / properties of a struct `a`.

**Comment by mossr** [comment]
This works for me on Windows 10 with Infultrator v1.0.3:
```julia
julia> using Infiltrator

julia> struct X
           i
           j
           k
       end

julia> function f(x)
           @infiltrate
           return x.i + x.j + x.k
       end
f (generic function with 1 method)

julia> x = X(1,2,3)
X(1, 2, 3)

julia> f(x)
Infiltrating f(x::X) at REPL[3]:2:

infil> x.
i j  k
```

**Comment by pfitzseb** [comment]
Yup, true. Works for me as well.

**Comment by mossr** [comment]
@pfitzseb by the way, I LOVE this package! Great work ❤️

**Comment by mossr** [comment]
@pfitzseb I made such a silly mistake, `x.<TAB>` only works because **_`x` is already a global variable_**....

Here's a MWE that _does not work_:
```julia
using Infiltrator

struct X
    i
    j
    k
end

function f(x)
    @infiltrate
end

x_global = X(1,2,3)

f(x_global)
```
then 

```julia
infil> x.
```
just blinks the `infil>` prompt without printing the field names.

You'll want to re-open this to track it.
