### ISSUE TITLE
Resetting breakpoints

### ISSUE THREAD

**Issue by PatMcFarlane** [JuliaDebug/Infiltrator.jl#48]
Love this package!  It's my default way of debugging now.

But it would be great if there was a way to turn back on breakpoints that have been shut-off with @toggle.   And also to turn everything back on after using @exit.  

The current process of having to end the julia session to reset these is very time consuming for big projects.

**Comment by pfitzseb** [comment]
There's `Infiltrator.clear_disabled!()`, which should do exactly that.

**Comment by PatMcFarlane** [comment]
Great thank you!
