### ISSUE TITLE
Infiltrator often does not work (no MWE)

### ISSUE THREAD

**Issue by bhalonen** [JuliaDebug/Infiltrator.jl#63]
I have a strange behavior in Infiltrator will occasionally stop, but often just skip right over the breakpoint.

Any ideas on how to promote the likelihood of the breakpoint being seen?

**Comment by pfitzseb** [comment]
Well, there are a few possibilities here:
- world age issues (an older, uninfiltrated, method is called instead)
- type instabilities causing another method to be called altogether
- the infiltrated method is called on another task (in which case the infiltration point is automatically disabled; this is printed to the terminal though)

Might also be worth clearing the set of disabled infiltration points with `Infiltrator.clear_disabled!()`.

**Comment by bhalonen** [comment]
now it works every time. I did nothing to fix it.... 
on the causes you listed
- It didnt work with a fresh restart often
- I had printout around the call, that showed the line getting hit

mysterious.

**Comment by bhalonen** [comment]
really beautiful package by the way.
