### ISSUE TITLE
Allow to break out to Julia REPL

### ISSUE THREAD

**Issue by dpsanders** [JuliaDebug/Infiltrator.jl#64]
Currently, if I am infiltrating at several points in my program and I find an issue, I need to repeatedly type `Ctrl-D` to leave the `infil>` REPL to get back to the top-level Julia REPL for Revise to kick in again once I modified something.

It would be great to be able to have a command to jump over all the infiltrator calls and get straight back to the Julia REPL. (I.e. "finish running with Infiltrator turned off").

**Comment by pfitzseb** [comment]
Doesn't `@exit` do just that?

**Comment by dpsanders** [comment]
Ah great, thanks!
