### ISSUE TITLE
Listing only the selected @locals

### ISSUE THREAD

**Issue by fpartl** [JuliaDebug/Infiltrator.jl#67]
Lets say some desperate imaginary programmer (me) is trying to debug his [Flux.jl](https://github.com/FluxML/Flux.jl) deep learning model. He places the `@infiltrate` macro in the training loop to, for example, determine only the size of the input data. But since the local environment contains a large model, a loaded data (`Flux.DataLoader` instance), model parameters, etc., it can take over a minute to run the `@locals` macro.

It would be very helpful to **dump only the selected local variables**. Alternatively, list only the type of variables.

For this dummy function: 
```julia
function model_test(model::VAE, device, loader, β::AbstractFloat)
    for seq ∈ loader
        x = seq[begin]; y = seq[end]

        @infiltrate
        μ, logσ, ŷ = model(x |> device)
        break
    end
end
```
`@locals` macro after some time gives
![obrazek](https://user-images.githubusercontent.com/22639820/159453379-d659b542-d6ff-48b6-bf24-03bc3a04be85.png)
which is absolutely excellent, but the evaluation takes a long time and much of it is not interesting at the moment. So something like `@locals seq y` would be great! The output would look like the following.
![image832](https://user-images.githubusercontent.com/22639820/159454718-b23c39fe-ce72-49f3-b470-5c7257ed660e.png)

Or did I miss something? In either case, thank you for your great work.

**Comment by pfitzseb** [comment]
I've implemented that in https://github.com/JuliaDebug/Infiltrator.jl/pull/68, but note that you can just enter `seq` or `y` in the prompt to inspect them.

**Comment by fpartl** [comment]
Wow! What a speed! Thank you! :+1: When should I expect a new release?

**Comment by pfitzseb** [comment]
As soon as GH actions (and therefore registry auto-merge) work again (check https://www.githubstatus.com/).
