### ISSUE TITLE
Also pass @__FILE__ and @__LINE__ to start_prompt

### ISSUE THREAD

**Issue by KristofferC** [JuliaDebug/Infiltrator.jl#7]
Would allow showing source code (like Debugger.jl does when debugging).

**Comment by pfitzseb** [comment]
https://github.com/JuliaDebug/Infiltrator.jl/pull/6 actually does that ;)
I agree that a `@body` (or whatever) invocation to show the current function would be nice to have. 

Might need to reconsider your request to make the default REPL mode more similar to Debugger's and not jump straight into a julia repl :P

**Comment by KristofferC** [comment]
I think it would be best to have a "functional interface" that doesn't know anything about REPLs, e.g.:

```
struct InfiltratorState
    locals
    stacktrace
    file
    line
end

function eval_code(::InfiltratorState, code)
     ...
end

function show_backtrace(::InfiltratorState)

end
```

This split then looks very much like how the backend in JuliaInterpreter is implemented, with different frontends putting their own REPLs in front of it.

**Comment by KristofferC** [comment]
I can do some refactoring to show what I mean.

**Comment by KristofferC** [comment]
Wtf, 2 space indentation :D

**Comment by pfitzseb** [comment]
> I think it would be best to have a "functional interface" that doesn't know anything about REPLs

Yeah, sounds good. I honestly just went with the simplest implementation here, but now that I think about it, we need a good interface for integration with Debugger/Juno.

> Yay, 2 space indentation, the much superior choice.

FTFY.

**Comment by KristofferC** [comment]
Tangentially, I don't really see the point in 

```
@infiltrate x > 3
```

over

```
x > 3 && @infiltrate
```
