### ISSUE TITLE
unreasonable behavior after `@exfiltrate`

### ISSUE THREAD

**Issue by thudjx** [JuliaDebug/Infiltrator.jl#76]
The mwe is:
```
function sum_f(ls::Vector{Float64})
    s = 0
    for x in ls
        s += f(x)
    end
    return s
end

function f(x::Float64)
    @infiltrate
    return sin(x)
end

ls = collect(range(0, stop=1, length=11))
sum_f(ls)
```
When I don't exfiltrate anything, the behavior at any point of `@infiltrate` is as expected:
```
infil> x
0.0
infil> @continue
infil> x
0.1
infil> @continue
infil> x
0.2
```
But if I `@exfiltrate x`, at the next point of `@infiltrate`, I cannot access `x` at this breaking point:
```
infil> @exfiltrate
Exfiltrating 1 local variable into the safehouse.
infil> @continue
infil> x
0.2
infil> @continue
infil> x
0.2
```
Although at this breaking point x is actually is:
```
infil> @locals
- x::Float64 = 0.4
```
I don't think this is deliberately designed to work like this, is it?

**Comment by pfitzseb** [comment]
Yeah, it's not. Wanna give https://github.com/JuliaDebug/Infiltrator.jl/pull/77 a go?
