### ISSUE TITLE
reenabling breakpoints

### ISSUE THREAD

**Issue by dafred94** [JuliaDebug/Infiltrator.jl#79]
Whenever I accidentally execute code containing `@infiltrate` from a file (shift+enter), my breakpoint is disabled.
What if I then want to reactivate those disabled breakpoints?
My current dirty workaround:
```
function reenable_bps()
    disabled = getfield(Infiltrator.store, :disabled)
    while !isempty(disabled)
        pop!(disabled)
    end
end


reenable_bps()
```
Is there something like a builtin `reenable_bps()`?

**Comment by pfitzseb** [comment]
`Infiltrator.clear_disabled!()` should do the trick.

**Comment by dafred94** [comment]
Ah good to know, thank you! I see it's only mentioned in the in-REPL help, maybe there would be a good place for it and other useful functions at the end of the README or so.

**Comment by pfitzseb** [comment]
https://juliadebug.github.io/Infiltrator.jl/dev/API/#Utility
