### ISSUE TITLE
infiltrating multithreaded code will wreak havoc

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaDebug/Infiltrator.jl#95]
Title is a bit exaggerated, but the following MWE will cause the REPL to become unusable (I also didn't find out how to exit gracefully):

```julia
julia> Threads.nthreads()
2

julia> using Infiltrator

julia> function f()
         Threads.@threads for i in 1:10
           a = i
           @infiltrate
         end
       end
f (generic function with 1 method)

julia> f()
```

**Comment by pfitzseb** [comment]
> I also didn't find out how to exit gracefully

keep spamming ^D :)

But yeah, can't say this is unexpected -- the failure mode is the same as for "normal" async code.
